import type { Category, DraftItem } from '../lib/types'

let _id = 0
function items(list: Array<[string, (string | undefined)?, (string | undefined)?, (string | undefined)?]>): DraftItem[] {
  return list.map(([name, subtitle, emoji, group]) => ({ id: `i${_id++}`, name, subtitle, emoji, group }))
}

export const CATEGORIES: Category[] = [
  {
    id: 'restaurants',
    name: 'Restaurants',
    emoji: '🍔',
    tagline: 'Draft your dream food court',
    gradient: 'from-orange-500 to-rose-500',
    groups: [
      { id: 'fast-food', name: 'Fast Food', emoji: '🍟' },
      { id: 'sit-down', name: 'Sit-Down', emoji: '🍽️' },
      { id: 'pizza-italian', name: 'Pizza & Italian', emoji: '🍕' },
      { id: 'dessert', name: 'Dessert & Treats', emoji: '🍩' },
      { id: 'coffee', name: 'Coffee & Cafe', emoji: '☕' },
    ],
    items: items([
      ['In-N-Out', 'Burgers', '🍔', 'fast-food'],
      ['Chipotle', 'Build-a-burrito', '🌯', 'fast-food'],
      ['Shake Shack', 'Burgers + shakes', '🥤', 'fast-food'],
      ['Chick-fil-A', 'Sandwiches', '🐔', 'fast-food'],
      ['Taco Bell', 'Late night legend', '🌮', 'fast-food'],
      ['Five Guys', 'Burgers + fries', '🍟', 'fast-food'],
      ['Panda Express', 'Orange chicken', '🥡', 'fast-food'],
      ['Raising Cane’s', 'Chicken fingers', '🍗', 'fast-food'],
      ['Popeyes', 'The chicken sandwich', '🍗', 'fast-food'],
      ['Wendy’s', 'Baconator', '🍔', 'fast-food'],
      ['McDonald’s', 'Golden arches', '🍟', 'fast-food'],
      ['Whataburger', 'Texas burgers', '🟧', 'fast-food'],
      ['Subway', 'Footlongs', '🥪', 'fast-food'],
      ['Olive Garden', 'Endless breadsticks', '🍝', 'sit-down'],
      ['Cheesecake Factory', 'The novel-menu', '🍰', 'sit-down'],
      ['Texas Roadhouse', 'Steaks + rolls', '🥩', 'sit-down'],
      ['IHOP', 'Pancakes 24/7', '🥞', 'sit-down'],
      ['Sweetgreen', 'Salad flex', '🥗', 'sit-down'],
      ['Waffle House', 'Scattered, smothered', '🧇', 'sit-down'],
      ['Buffalo Wild Wings', 'Wings + games', '🍗', 'sit-down'],
      ['Red Lobster', 'Cheddar biscuits', '🦞', 'sit-down'],
      ['Chili’s', 'Triple dipper', '🌶️', 'sit-down'],
      ['Outback Steakhouse', 'Bloomin’ onion', '🧅', 'sit-down'],
      ['Domino’s', 'Pizza', '🍕', 'pizza-italian'],
      ['Pizza Hut', 'Stuffed crust', '🧀', 'pizza-italian'],
      ['Papa John’s', 'Better ingredients', '🍕', 'pizza-italian'],
      ['Little Caesars', 'Hot-N-Ready', '🟧', 'pizza-italian'],
      ['Buca di Beppo', 'Family-style Italian', '🍝', 'pizza-italian'],
      ['Dairy Queen', 'Blizzards', '🍦', 'dessert'],
      ['Cinnabon', 'Cinnamon rolls', '🌀', 'dessert'],
      ['Krispy Kreme', 'Hot now', '🍩', 'dessert'],
      ['Baskin-Robbins', '31 flavors', '🍨', 'dessert'],
      ['Cold Stone Creamery', 'Mix-ins', '🍧', 'dessert'],
      ['Starbucks', 'Pumpkin spice', '☕', 'coffee'],
      ['Dunkin’', 'America runs on it', '🍩', 'coffee'],
      ['Tim Hortons', 'Double-double', '🇨🇦', 'coffee'],
      ['Peet’s Coffee', 'Dark roast', '☕', 'coffee'],
    ]),
  },
  {
    id: 'nfl',
    name: 'NFL Teams',
    emoji: '🏈',
    tagline: 'Build the league from scratch',
    gradient: 'from-emerald-500 to-teal-500',
    groups: [
      { id: 'afc-east', name: 'AFC East', emoji: '🔵' },
      { id: 'afc-other', name: 'AFC West/North/South', emoji: '🔴' },
      { id: 'nfc-east', name: 'NFC East', emoji: '⭐' },
      { id: 'nfc-other', name: 'NFC West/North/South', emoji: '🟢' },
    ],
    items: items([
      ['Bills', 'Buffalo', '🦬', 'afc-east'],
      ['Dolphins', 'Miami', '🐬', 'afc-east'],
      ['Patriots', 'New England', '🔱', 'afc-east'],
      ['Jets', 'New York', '🛩️', 'afc-east'],
      ['Chiefs', 'Kansas City', '🔴', 'afc-other'],
      ['Ravens', 'Baltimore', '🐦‍⬛', 'afc-other'],
      ['Bengals', 'Cincinnati', '🐅', 'afc-other'],
      ['Steelers', 'Pittsburgh', '⚫', 'afc-other'],
      ['Jaguars', 'Jacksonville', '🐆', 'afc-other'],
      ['Chargers', 'Los Angeles', '⚡', 'afc-other'],
      ['Browns', 'Cleveland', '🟤', 'afc-other'],
      ['Texans', 'Houston', '🐂', 'afc-other'],
      ['Broncos', 'Denver', '🐴', 'afc-other'],
      ['Raiders', 'Las Vegas', '☠️', 'afc-other'],
      ['Colts', 'Indianapolis', '🐎', 'afc-other'],
      ['Titans', 'Tennessee', '🗡️', 'afc-other'],
      ['Cowboys', 'Dallas', '⭐', 'nfc-east'],
      ['Eagles', 'Philadelphia', '🦅', 'nfc-east'],
      ['Commanders', 'Washington', '🏛️', 'nfc-east'],
      ['Giants', 'New York', '🗽', 'nfc-east'],
      ['49ers', 'San Francisco', '⛏️', 'nfc-other'],
      ['Lions', 'Detroit', '🦁', 'nfc-other'],
      ['Packers', 'Green Bay', '🧀', 'nfc-other'],
      ['Vikings', 'Minnesota', '🛡️', 'nfc-other'],
      ['Seahawks', 'Seattle', '🦅', 'nfc-other'],
      ['Bears', 'Chicago', '🐻', 'nfc-other'],
      ['Rams', 'Los Angeles', '🐏', 'nfc-other'],
      ['Buccaneers', 'Tampa Bay', '🏴‍☠️', 'nfc-other'],
      ['Saints', 'New Orleans', '⚜️', 'nfc-other'],
      ['Falcons', 'Atlanta', '🐦', 'nfc-other'],
      ['Panthers', 'Carolina', '🐆', 'nfc-other'],
      ['Cardinals', 'Arizona', '🐦', 'nfc-other'],
    ]),
  },
  {
    id: 'movies',
    name: 'Movies',
    emoji: '🍿',
    tagline: 'Draft the ultimate watchlist',
    gradient: 'from-fuchsia-500 to-purple-600',
    groups: [
      { id: 'action', name: 'Action', emoji: '💥' },
      { id: 'drama', name: 'Drama', emoji: '🎭' },
      { id: 'scifi', name: 'Sci-Fi', emoji: '🚀' },
      { id: 'comedy', name: 'Comedy', emoji: '😂' },
      { id: 'animation', name: 'Animation', emoji: '🎨' },
    ],
    items: items([
      ['The Dark Knight', '2008', '🦇', 'action'],
      ['Mad Max: Fury Road', '2015', '🏜️', 'action'],
      ['Gladiator', '2000', '🗡️', 'action'],
      ['John Wick', '2014', '🔫', 'action'],
      ['Die Hard', '1988', '🎄', 'action'],
      ['Top Gun: Maverick', '2022', '✈️', 'action'],
      ['Mission: Impossible', '1996', '🕶️', 'action'],
      ['The Godfather', '1972', '🍷', 'drama'],
      ['Pulp Fiction', '1994', '🔫', 'drama'],
      ['Parasite', '2019', '🪜', 'drama'],
      ['Forrest Gump', '1994', '🍫', 'drama'],
      ['Goodfellas', '1990', '🃏', 'drama'],
      ['Whiplash', '2014', '🥁', 'drama'],
      ['The Shawshank Redemption', '1994', '🔨', 'drama'],
      ['Schindler’s List', '1993', '🕯️', 'drama'],
      ['Inception', '2010', '🌀', 'scifi'],
      ['Interstellar', '2014', '🚀', 'scifi'],
      ['The Matrix', '1999', '💊', 'scifi'],
      ['Blade Runner 2049', '2017', '🌃', 'scifi'],
      ['Dune', '2021', '🏜️', 'scifi'],
      ['Jurassic Park', '1993', '🦖', 'scifi'],
      ['Arrival', '2016', '🛸', 'scifi'],
      ['Get Out', '2017', '🫖', 'scifi'],
      ['Everything Everywhere', '2022', '🥯', 'comedy'],
      ['Superbad', '2007', '🍺', 'comedy'],
      ['The Grand Budapest Hotel', '2014', '🏨', 'comedy'],
      ['Step Brothers', '2008', '🛏️', 'comedy'],
      ['Anchorman', '2004', '📺', 'comedy'],
      ['Bridesmaids', '2011', '👰', 'comedy'],
      ['Spirited Away', '2001', '🐉', 'animation'],
      ['Toy Story', '1995', '🤠', 'animation'],
      ['Spider-Man: Into the Spider-Verse', '2018', '🕸️', 'animation'],
      ['The Lion King', '1994', '🦁', 'animation'],
      ['Up', '2009', '🎈', 'animation'],
      ['Coco', '2017', '💀', 'animation'],
      ['Shrek', '2001', '🧅', 'animation'],
    ]),
  },
  {
    id: 'travel',
    name: 'Travel Spots',
    emoji: '✈️',
    tagline: 'Draft your bucket list',
    gradient: 'from-sky-500 to-blue-600',
    groups: [
      { id: 'europe', name: 'Europe', emoji: '🏰' },
      { id: 'asia', name: 'Asia', emoji: '⛩️' },
      { id: 'americas', name: 'Americas', emoji: '🌎' },
      { id: 'beach-islands', name: 'Beaches & Islands', emoji: '🏝️' },
      { id: 'nature', name: 'Nature & Adventure', emoji: '🏔️' },
    ],
    items: items([
      ['Paris', 'France', '🗼', 'europe'],
      ['Rome', 'Italy', '🏛️', 'europe'],
      ['Barcelona', 'Spain', '🏖️', 'europe'],
      ['Santorini', 'Greece', '🇬🇷', 'europe'],
      ['Lisbon', 'Portugal', '🚋', 'europe'],
      ['London', 'England', '🎡', 'europe'],
      ['Amsterdam', 'Netherlands', '🚲', 'europe'],
      ['Prague', 'Czechia', '🏰', 'europe'],
      ['Tokyo', 'Japan', '🗼', 'asia'],
      ['Kyoto', 'Japan', '⛩️', 'asia'],
      ['Bangkok', 'Thailand', '🛕', 'asia'],
      ['Singapore', 'Singapore', '🌆', 'asia'],
      ['Hong Kong', 'China', '🏙️', 'asia'],
      ['Seoul', 'South Korea', '🏯', 'asia'],
      ['New York', 'USA', '🗽', 'americas'],
      ['Rio de Janeiro', 'Brazil', '🎉', 'americas'],
      ['Mexico City', 'Mexico', '🌮', 'americas'],
      ['Buenos Aires', 'Argentina', '💃', 'americas'],
      ['Vancouver', 'Canada', '🍁', 'americas'],
      ['Cusco', 'Peru', '🏔️', 'americas'],
      ['Bali', 'Indonesia', '🏝️', 'beach-islands'],
      ['Maldives', 'Maldives', '🐠', 'beach-islands'],
      ['Maui', 'Hawaii', '🌺', 'beach-islands'],
      ['Bora Bora', 'French Polynesia', '🥥', 'beach-islands'],
      ['Phuket', 'Thailand', '🌴', 'beach-islands'],
      ['Reykjavik', 'Iceland', '🌋', 'nature'],
      ['Cape Town', 'South Africa', '⛰️', 'nature'],
      ['Queenstown', 'New Zealand', '🪂', 'nature'],
      ['Banff', 'Canada', '🏔️', 'nature'],
      ['Patagonia', 'Argentina/Chile', '🥾', 'nature'],
      ['Marrakech', 'Morocco', '🕌', 'nature'],
      ['Swiss Alps', 'Switzerland', '🏔️', 'nature'],
    ]),
  },
  {
    id: 'icecream',
    name: 'Ice Cream',
    emoji: '🍦',
    tagline: 'Scoop the perfect lineup',
    gradient: 'from-pink-400 to-rose-400',
    groups: [
      { id: 'classic', name: 'Classics', emoji: '🍨' },
      { id: 'chocolatey', name: 'Chocolatey', emoji: '🍫' },
      { id: 'fruity', name: 'Fruity & Sorbet', emoji: '🍓' },
      { id: 'loaded', name: 'Loaded & Mix-ins', emoji: '🍪' },
    ],
    items: items([
      ['Vanilla', 'don’t sleep on it', '🤍', 'classic'],
      ['Chocolate', undefined, '🍫', 'classic'],
      ['Strawberry', undefined, '🍓', 'classic'],
      ['Coffee', undefined, '☕', 'classic'],
      ['Neapolitan', undefined, '🟤', 'classic'],
      ['Butter Pecan', undefined, '🧈', 'classic'],
      ['Pistachio', undefined, '🥜', 'classic'],
      ['Cookies & Cream', undefined, '🍪', 'chocolatey'],
      ['Mint Choc Chip', undefined, '🌱', 'chocolatey'],
      ['Chocolate Fudge Brownie', undefined, '🍫', 'chocolatey'],
      ['Double Chocolate', undefined, '🟫', 'chocolatey'],
      ['Chocolate Chip', undefined, '🍫', 'chocolatey'],
      ['Mocha Almond Fudge', undefined, '☕', 'chocolatey'],
      ['Mango Sorbet', undefined, '🥭', 'fruity'],
      ['Raspberry Sorbet', undefined, '🫐', 'fruity'],
      ['Lemon Sorbet', undefined, '🍋', 'fruity'],
      ['Strawberry Cheesecake', undefined, '🍰', 'fruity'],
      ['Peach', undefined, '🍑', 'fruity'],
      ['Coconut', undefined, '🥥', 'fruity'],
      ['Cookie Dough', undefined, '🍪', 'loaded'],
      ['Salted Caramel', undefined, '🧂', 'loaded'],
      ['Rocky Road', undefined, '🪨', 'loaded'],
      ['Birthday Cake', undefined, '🎂', 'loaded'],
      ['Moose Tracks', undefined, '🫎', 'loaded'],
      ['Cherry Garcia', undefined, '🍒', 'loaded'],
      ['Phish Food', undefined, '🐟', 'loaded'],
      ['Half Baked', undefined, '🥄', 'loaded'],
      ['Caramel Praline', undefined, '🥜', 'loaded'],
    ]),
  },
  {
    id: 'games',
    name: 'Video Games',
    emoji: '🎮',
    tagline: 'Draft the GOAT library',
    gradient: 'from-indigo-500 to-violet-600',
    groups: [
      { id: 'adventure-rpg', name: 'Adventure & RPG', emoji: '⚔️' },
      { id: 'action', name: 'Action', emoji: '💥' },
      { id: 'indie', name: 'Indie', emoji: '🎲' },
      { id: 'multiplayer', name: 'Multiplayer', emoji: '🌐' },
      { id: 'cozy-puzzle', name: 'Cozy & Puzzle', emoji: '🧩' },
    ],
    items: items([
      ['The Legend of Zelda: BOTW', undefined, '🗡️', 'adventure-rpg'],
      ['Elden Ring', undefined, '⚔️', 'adventure-rpg'],
      ['The Witcher 3', undefined, '🐺', 'adventure-rpg'],
      ['Skyrim', undefined, '🐉', 'adventure-rpg'],
      ['Baldur’s Gate 3', undefined, '🎲', 'adventure-rpg'],
      ['Final Fantasy VII', undefined, '⚔️', 'adventure-rpg'],
      ['God of War', undefined, '🪓', 'action'],
      ['Red Dead Redemption 2', undefined, '🤠', 'action'],
      ['Grand Theft Auto V', undefined, '🚗', 'action'],
      ['The Last of Us', undefined, '🍄', 'action'],
      ['Super Mario Odyssey', undefined, '🍄', 'action'],
      ['Spider-Man 2', undefined, '🕸️', 'action'],
      ['Hollow Knight', undefined, '🪲', 'indie'],
      ['Hades', undefined, '🔥', 'indie'],
      ['Celeste', undefined, '🏔️', 'indie'],
      ['Stardew Valley', undefined, '🌾', 'indie'],
      ['Undertale', undefined, '❤️', 'indie'],
      ['Cuphead', undefined, '☕', 'indie'],
      ['Minecraft', undefined, '⛏️', 'multiplayer'],
      ['Fortnite', undefined, '🪂', 'multiplayer'],
      ['Mario Kart 8', undefined, '🏎️', 'multiplayer'],
      ['Counter-Strike 2', undefined, '🔫', 'multiplayer'],
      ['League of Legends', undefined, '🏆', 'multiplayer'],
      ['Overwatch 2', undefined, '🎯', 'multiplayer'],
      ['Rocket League', undefined, '🚀', 'multiplayer'],
      ['Portal 2', undefined, '🟠', 'cozy-puzzle'],
      ['Tetris', undefined, '🟦', 'cozy-puzzle'],
      ['Animal Crossing', undefined, '🍃', 'cozy-puzzle'],
      ['The Sims 4', undefined, '🏠', 'cozy-puzzle'],
      ['Baba Is You', undefined, '🐑', 'cozy-puzzle'],
    ]),
  },
  {
    id: 'snacks',
    name: 'Snacks',
    emoji: '🍿',
    tagline: 'Stock the ultimate pantry',
    gradient: 'from-amber-500 to-orange-600',
    groups: [
      { id: 'chips', name: 'Chips & Crisps', emoji: '🥔' },
      { id: 'crackers', name: 'Crackers', emoji: '🧀' },
      { id: 'sweet', name: 'Sweet', emoji: '🍪' },
      { id: 'salty-savory', name: 'Salty & Savory', emoji: '🥨' },
    ],
    items: items([
      ['Doritos', 'Nacho Cheese', '🔺', 'chips'],
      ['Pringles', undefined, '🥫', 'chips'],
      ['Lay’s', 'Classic', '🥔', 'chips'],
      ['Ruffles', undefined, '〰️', 'chips'],
      ['Takis', undefined, '🌶️', 'chips'],
      ['Cheetos', undefined, '🐆', 'chips'],
      ['Sun Chips', undefined, '☀️', 'chips'],
      ['Tostitos', undefined, '🔺', 'chips'],
      ['Goldfish', undefined, '🐠', 'crackers'],
      ['Cheez-Its', undefined, '🧀', 'crackers'],
      ['Ritz', undefined, '⭕', 'crackers'],
      ['Triscuit', undefined, '🌾', 'crackers'],
      ['Wheat Thins', undefined, '🟫', 'crackers'],
      ['Saltines', undefined, '🧂', 'crackers'],
      ['Oreos', undefined, '🍪', 'sweet'],
      ['Pop-Tarts', undefined, '🍓', 'sweet'],
      ['Reese’s', undefined, '🥜', 'sweet'],
      ['Sour Patch Kids', undefined, '😝', 'sweet'],
      ['Skittles', undefined, '🌈', 'sweet'],
      ['Rice Krispies Treats', undefined, '🍚', 'sweet'],
      ['Fruit Snacks', undefined, '🍇', 'sweet'],
      ['Chips Ahoy!', undefined, '🍫', 'sweet'],
      ['Combos', undefined, '🥨', 'salty-savory'],
      ['Trail Mix', undefined, '🥜', 'salty-savory'],
      ['Beef Jerky', undefined, '🥩', 'salty-savory'],
      ['Pretzels', undefined, '🥨', 'salty-savory'],
      ['Popcorn', undefined, '🍿', 'salty-savory'],
      ['Pepperoni Sticks', undefined, '🌭', 'salty-savory'],
      ['Pistachios', undefined, '🌰', 'salty-savory'],
      ['Hummus & Pita', undefined, '🫓', 'salty-savory'],
    ]),
  },
  {
    id: 'pets',
    name: 'Dog Breeds',
    emoji: '🐶',
    tagline: 'Assemble the goodest boys',
    gradient: 'from-yellow-500 to-amber-600',
    groups: [
      { id: 'big', name: 'Big Dogs', emoji: '🐕' },
      { id: 'small', name: 'Small Dogs', emoji: '🐩' },
      { id: 'working', name: 'Working & Herding', emoji: '🦮' },
      { id: 'family', name: 'Family Favorites', emoji: '🏡' },
    ],
    items: items([
      ['Great Dane', undefined, '🦒', 'big'],
      ['Husky', undefined, '🐺', 'big'],
      ['Rottweiler', undefined, '🦴', 'big'],
      ['Doberman', undefined, '⚡', 'big'],
      ['Mastiff', undefined, '🛡️', 'big'],
      ['Saint Bernard', undefined, '🏔️', 'big'],
      ['Corgi', undefined, '🌭', 'small'],
      ['French Bulldog', undefined, '🦇', 'small'],
      ['Dachshund', undefined, '🌭', 'small'],
      ['Pug', undefined, '😤', 'small'],
      ['Pomeranian', undefined, '☁️', 'small'],
      ['Chihuahua', undefined, '🫨', 'small'],
      ['Shih Tzu', undefined, '🎀', 'small'],
      ['Yorkshire Terrier', undefined, '🎀', 'small'],
      ['Border Collie', undefined, '🧠', 'working'],
      ['Australian Shepherd', undefined, '🐑', 'working'],
      ['German Shepherd', undefined, '👮', 'working'],
      ['Belgian Malinois', undefined, '🎯', 'working'],
      ['Shiba Inu', undefined, '🔥', 'working'],
      ['Cattle Dog', undefined, '🐄', 'working'],
      ['Golden Retriever', undefined, '🦮', 'family'],
      ['Labrador', undefined, '🦴', 'family'],
      ['Beagle', undefined, '👃', 'family'],
      ['Bernese Mountain Dog', undefined, '⛰️', 'family'],
      ['Cavalier King Charles', undefined, '👑', 'family'],
      ['Boxer', undefined, '🥊', 'family'],
      ['Poodle', undefined, '🎩', 'family'],
      ['Cocker Spaniel', undefined, '🐾', 'family'],
    ]),
  },
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🦁',
    tagline: 'Draft your wild kingdom',
    gradient: 'from-lime-500 to-green-600',
    groups: [
      { id: 'predators', name: 'Predators', emoji: '🦁' },
      { id: 'sea', name: 'Sea Life', emoji: '🐬' },
      { id: 'birds', name: 'Birds', emoji: '🦅' },
      { id: 'exotic', name: 'Exotic & Jungle', emoji: '🦍' },
      { id: 'cute', name: 'Cute & Cuddly', emoji: '🐼' },
    ],
    items: items([
      ['Lion', 'King of the jungle', '🦁', 'predators'],
      ['Tiger', undefined, '🐅', 'predators'],
      ['Wolf', undefined, '🐺', 'predators'],
      ['Cheetah', 'Fastest land animal', '🐆', 'predators'],
      ['Leopard', undefined, '🐆', 'predators'],
      ['Bear', undefined, '🐻', 'predators'],
      ['Crocodile', undefined, '🐊', 'predators'],
      ['Dolphin', undefined, '🐬', 'sea'],
      ['Octopus', undefined, '🐙', 'sea'],
      ['Shark', undefined, '🦈', 'sea'],
      ['Whale', undefined, '🐋', 'sea'],
      ['Sea Turtle', undefined, '🐢', 'sea'],
      ['Jellyfish', undefined, '🪼', 'sea'],
      ['Seahorse', undefined, '🌊', 'sea'],
      ['Eagle', undefined, '🦅', 'birds'],
      ['Owl', undefined, '🦉', 'birds'],
      ['Penguin', undefined, '🐧', 'birds'],
      ['Flamingo', undefined, '🦩', 'birds'],
      ['Peacock', undefined, '🦚', 'birds'],
      ['Parrot', undefined, '🦜', 'birds'],
      ['Elephant', undefined, '🐘', 'exotic'],
      ['Gorilla', undefined, '🦍', 'exotic'],
      ['Kangaroo', undefined, '🦘', 'exotic'],
      ['Giraffe', undefined, '🦒', 'exotic'],
      ['Rhino', undefined, '🦏', 'exotic'],
      ['Sloth', undefined, '🦥', 'exotic'],
      ['Panda', undefined, '🐼', 'cute'],
      ['Fox', undefined, '🦊', 'cute'],
      ['Otter', undefined, '🦦', 'cute'],
      ['Red Panda', undefined, '🍁', 'cute'],
      ['Koala', undefined, '🐨', 'cute'],
      ['Hedgehog', undefined, '🦔', 'cute'],
    ]),
  },
  {
    id: 'footballers',
    name: 'Football Players',
    emoji: '🏈',
    tagline: 'Draft your NFL dream team',
    gradient: 'from-red-500 to-orange-600',
    groups: [
      { id: 'qb', name: 'Quarterbacks', emoji: '🎯' },
      { id: 'skill', name: 'WR / RB / TE', emoji: '💨' },
      { id: 'defense', name: 'Defense', emoji: '🛡️' },
      { id: 'legends', name: 'Legends', emoji: '🐐' },
    ],
    items: items([
      ['Patrick Mahomes', 'QB · Chiefs', '🐐', 'qb'],
      ['Josh Allen', 'QB · Bills', '🦬', 'qb'],
      ['Lamar Jackson', 'QB · Ravens', '⚡', 'qb'],
      ['Joe Burrow', 'QB · Bengals', '🐅', 'qb'],
      ['Jalen Hurts', 'QB · Eagles', '🦅', 'qb'],
      ['Justin Herbert', 'QB · Chargers', '⚡', 'qb'],
      ['C.J. Stroud', 'QB · Texans', '🐂', 'qb'],
      ['Justin Jefferson', 'WR · Vikings', '🎯', 'skill'],
      ['Tyreek Hill', 'WR · Dolphins', '💨', 'skill'],
      ['Ja’Marr Chase', 'WR · Bengals', '🔥', 'skill'],
      ['CeeDee Lamb', 'WR · Cowboys', '⭐', 'skill'],
      ['A.J. Brown', 'WR · Eagles', '🦅', 'skill'],
      ['Travis Kelce', 'TE · Chiefs', '🎉', 'skill'],
      ['Christian McCaffrey', 'RB · 49ers', '🏃', 'skill'],
      ['Saquon Barkley', 'RB · Eagles', '💪', 'skill'],
      ['Derrick Henry', 'RB · Ravens', '🚂', 'skill'],
      ['Bijan Robinson', 'RB · Falcons', '⚡', 'skill'],
      ['Micah Parsons', 'LB · Cowboys', '😤', 'defense'],
      ['Myles Garrett', 'DE · Browns', '🦾', 'defense'],
      ['T.J. Watt', 'LB · Steelers', '⚫', 'defense'],
      ['Nick Bosa', 'DE · 49ers', '⛏️', 'defense'],
      ['Aaron Donald', 'DT · Legend', '🪨', 'defense'],
      ['Sauce Gardner', 'CB · Jets', '🌶️', 'defense'],
      ['Fred Warner', 'LB · 49ers', '🛡️', 'defense'],
      ['Patrick Surtain II', 'CB · Broncos', '🔒', 'defense'],
      ['Tom Brady', 'QB · Legend', '🐐', 'legends'],
      ['Jerry Rice', 'WR · Legend', '🙌', 'legends'],
      ['Peyton Manning', 'QB · Legend', '🤙', 'legends'],
      ['Barry Sanders', 'RB · Legend', '🌀', 'legends'],
      ['Lawrence Taylor', 'LB · Legend', '😈', 'legends'],
      ['Randy Moss', 'WR · Legend', '🌙', 'legends'],
      ['Ray Lewis', 'LB · Legend', '🔥', 'legends'],
    ]),
  },
  {
    id: 'mascots',
    name: 'Mascots',
    emoji: '🐯',
    tagline: 'Draft the most iconic sideline weirdos',
    gradient: 'from-green-500 to-emerald-600',
    groups: [
      { id: 'mlb', name: 'MLB', emoji: '⚾' },
      { id: 'nba', name: 'NBA', emoji: '🏀' },
      { id: 'nfl', name: 'NFL', emoji: '🏈' },
      { id: 'nhl', name: 'NHL', emoji: '🏒' },
    ],
    items: items([
      ['Phillie Phanatic', 'Phillies', '🟢', 'mlb'],
      ['Mr. Met', 'Mets', '⚾', 'mlb'],
      ['San Diego Chicken', 'Padres', '🐔', 'mlb'],
      ['Wally the Green Monster', 'Red Sox', '👹', 'mlb'],
      ['Bernie Brewer', 'Brewers', '🍺', 'mlb'],
      ['Sluggerrr', 'Royals', '🦁', 'mlb'],
      ['Fredbird', 'Cardinals', '🔴', 'mlb'],
      ['Orbit', 'Astros', '🛸', 'mlb'],
      ['Benny the Bull', 'Bulls', '🐂', 'nba'],
      ['Rocky', 'Nuggets', '🦁', 'nba'],
      ['Burnie', 'Heat', '🔥', 'nba'],
      ['The Gorilla', 'Suns', '🦍', 'nba'],
      ['Stuff the Magic Dragon', 'Magic', '🐉', 'nba'],
      ['Clutch', 'Rockets', '🐻', 'nba'],
      ['Hugo', 'Hornets', '🐝', 'nba'],
      ['Bango', 'Bucks', '🦌', 'nba'],
      ['Swoop', 'Eagles', '🦅', 'nfl'],
      ['Billy Buffalo', 'Bills', '🦬', 'nfl'],
      ['Big Red', 'Cardinals', '🔴', 'nfl'],
      ['Roary', 'Lions', '🦁', 'nfl'],
      ['T.D.', 'Dolphins', '🐬', 'nfl'],
      ['Sir Saint', 'Saints', '⚜️', 'nfl'],
      ['Pat Patriot', 'Patriots', '🔱', 'nfl'],
      ['Gritty', 'Flyers', '🟠', 'nhl'],
      ['Youppi!', 'Canadiens', '🧡', 'nhl'],
      ['Stanley C. Panther', 'Panthers', '🐆', 'nhl'],
      ['Bernie', 'Avalanche', '🐺', 'nhl'],
      ['Spartacat', 'Senators', '🐱', 'nhl'],
      ['Iceburgh', 'Penguins', '🐧', 'nhl'],
      ['S.J. Sharkie', 'Sharks', '🦈', 'nhl'],
    ]),
  },
  {
    id: 'nba',
    name: 'NBA Players',
    emoji: '🏀',
    tagline: 'Build a starting five (and a bench)',
    gradient: 'from-orange-500 to-amber-600',
    groups: [
      { id: 'guards', name: 'Guards', emoji: '🎯' },
      { id: 'wings', name: 'Wings', emoji: '🪽' },
      { id: 'bigs', name: 'Bigs', emoji: '🗼' },
      { id: 'legends', name: 'Legends', emoji: '🐐' },
    ],
    items: items([
      ['Stephen Curry', 'Warriors', '🎯', 'guards'],
      ['Luka Dončić', 'Mavericks', '🪄', 'guards'],
      ['Shai Gilgeous-Alexander', 'Thunder', '⚡', 'guards'],
      ['Damian Lillard', 'Bucks', '⏰', 'guards'],
      ['Ja Morant', 'Grizzlies', '🐻', 'guards'],
      ['Devin Booker', 'Suns', '☀️', 'guards'],
      ['Donovan Mitchell', 'Cavaliers', '🕷️', 'guards'],
      ['Anthony Edwards', 'Timberwolves', '🐺', 'guards'],
      ['LeBron James', 'Lakers', '👑', 'wings'],
      ['Kevin Durant', 'Suns', '🐍', 'wings'],
      ['Jayson Tatum', 'Celtics', '☘️', 'wings'],
      ['Jimmy Butler', 'Heat', '🔥', 'wings'],
      ['Kawhi Leonard', 'Clippers', '🤖', 'wings'],
      ['Paul George', 'Clippers', '🌴', 'wings'],
      ['Jaylen Brown', 'Celtics', '☘️', 'wings'],
      ['Giannis Antetokounmpo', 'Bucks', '🦌', 'bigs'],
      ['Nikola Jokić', 'Nuggets', '🃏', 'bigs'],
      ['Joel Embiid', '76ers', '🔱', 'bigs'],
      ['Victor Wembanyama', 'Spurs', '🛸', 'bigs'],
      ['Anthony Davis', 'Lakers', '🌑', 'bigs'],
      ['Bam Adebayo', 'Heat', '🔥', 'bigs'],
      ['Karl-Anthony Towns', 'Knicks', '🗽', 'bigs'],
      ['Michael Jordan', 'Bulls', '🐐', 'legends'],
      ['Kobe Bryant', 'Lakers', '🐍', 'legends'],
      ['Magic Johnson', 'Lakers', '✨', 'legends'],
      ['Larry Bird', 'Celtics', '🦅', 'legends'],
      ['Shaquille O’Neal', 'Lakers', '🦾', 'legends'],
      ['Tim Duncan', 'Spurs', '🏛️', 'legends'],
      ['Hakeem Olajuwon', 'Rockets', '🌀', 'legends'],
      ['Allen Iverson', '76ers', '🩹', 'legends'],
    ]),
  },
  {
    id: 'soccer',
    name: 'Soccer Players',
    emoji: '⚽',
    tagline: 'Assemble the global XI',
    gradient: 'from-teal-500 to-cyan-600',
    groups: [
      { id: 'forwards', name: 'Forwards', emoji: '🥅' },
      { id: 'midfielders', name: 'Midfielders', emoji: '🎩' },
      { id: 'defenders', name: 'Defenders & GK', emoji: '🧤' },
      { id: 'legends', name: 'Legends', emoji: '🐐' },
    ],
    items: items([
      ['Kylian Mbappé', 'Real Madrid', '🚀', 'forwards'],
      ['Erling Haaland', 'Man City', '🤖', 'forwards'],
      ['Vinícius Jr.', 'Real Madrid', '✨', 'forwards'],
      ['Mohamed Salah', 'Liverpool', '🇪🇬', 'forwards'],
      ['Harry Kane', 'Bayern', '🎯', 'forwards'],
      ['Robert Lewandowski', 'Barcelona', '🇵🇱', 'forwards'],
      ['Lamine Yamal', 'Barcelona', '🌟', 'forwards'],
      ['Lautaro Martínez', 'Inter', '🇦🇷', 'forwards'],
      ['Kevin De Bruyne', 'Man City', '🎯', 'midfielders'],
      ['Jude Bellingham', 'Real Madrid', '🦄', 'midfielders'],
      ['Pedri', 'Barcelona', '🎩', 'midfielders'],
      ['Rodri', 'Man City', '🛡️', 'midfielders'],
      ['Bukayo Saka', 'Arsenal', '⭐', 'midfielders'],
      ['Son Heung-min', 'Tottenham', '🇰🇷', 'midfielders'],
      ['Phil Foden', 'Man City', '🔵', 'midfielders'],
      ['Florian Wirtz', 'Liverpool', '🇩🇪', 'midfielders'],
      ['Virgil van Dijk', 'Liverpool', '🧱', 'defenders'],
      ['Rúben Dias', 'Man City', '🛡️', 'defenders'],
      ['Achraf Hakimi', 'PSG', '🇲🇦', 'defenders'],
      ['Alphonso Davies', 'Bayern', '🇨🇦', 'defenders'],
      ['William Saliba', 'Arsenal', '🧱', 'defenders'],
      ['Thibaut Courtois', 'Real Madrid', '🧤', 'defenders'],
      ['Alisson', 'Liverpool', '🧤', 'defenders'],
      ['Lionel Messi', 'Inter Miami', '🐐', 'legends'],
      ['Cristiano Ronaldo', 'Al Nassr', '🇵🇹', 'legends'],
      ['Neymar', 'Santos', '🇧🇷', 'legends'],
      ['Ronaldinho', 'Brazil', '🪄', 'legends'],
      ['Zinedine Zidane', 'France', '🎩', 'legends'],
      ['Pelé', 'Brazil', '👑', 'legends'],
      ['Diego Maradona', 'Argentina', '✋', 'legends'],
    ]),
  },
  {
    id: 'superheroes',
    name: 'Superheroes',
    emoji: '🦸',
    tagline: 'Draft your Avengers',
    gradient: 'from-red-500 to-rose-600',
    groups: [
      { id: 'marvel', name: 'Marvel', emoji: '🕷️' },
      { id: 'dc', name: 'DC', emoji: '🦇' },
      { id: 'xmen', name: 'X-Men', emoji: '🧬' },
      { id: 'villains', name: 'Villains', emoji: '😈' },
    ],
    items: items([
      ['Spider-Man', undefined, '🕷️', 'marvel'],
      ['Iron Man', undefined, '🤖', 'marvel'],
      ['Thor', undefined, '🔨', 'marvel'],
      ['Hulk', undefined, '💚', 'marvel'],
      ['Black Panther', undefined, '🐈‍⬛', 'marvel'],
      ['Captain America', undefined, '🛡️', 'marvel'],
      ['Doctor Strange', undefined, '🌀', 'marvel'],
      ['Spider-Gwen', undefined, '🕸️', 'marvel'],
      ['Captain Marvel', undefined, '⭐', 'marvel'],
      ['Batman', undefined, '🦇', 'dc'],
      ['Superman', undefined, '🦸', 'dc'],
      ['Wonder Woman', undefined, '👑', 'dc'],
      ['Flash', undefined, '⚡', 'dc'],
      ['Aquaman', undefined, '🔱', 'dc'],
      ['Green Lantern', undefined, '💚', 'dc'],
      ['Nightwing', undefined, '🌃', 'dc'],
      ['Shazam', undefined, '⚡', 'dc'],
      ['Wolverine', undefined, '🐾', 'xmen'],
      ['Storm', undefined, '🌩️', 'xmen'],
      ['Cyclops', undefined, '🔴', 'xmen'],
      ['Jean Grey', undefined, '🔥', 'xmen'],
      ['Professor X', undefined, '🧠', 'xmen'],
      ['Magneto', undefined, '🧲', 'xmen'],
      ['Beast', undefined, '🦍', 'xmen'],
      ['Nightcrawler', undefined, '💨', 'xmen'],
      ['Thanos', undefined, '🧤', 'villains'],
      ['Joker', undefined, '🃏', 'villains'],
      ['Loki', undefined, '🐍', 'villains'],
      ['Green Goblin', undefined, '🎃', 'villains'],
      ['Lex Luthor', undefined, '💼', 'villains'],
      ['Venom', undefined, '👅', 'villains'],
      ['Doctor Doom', undefined, '🤺', 'villains'],
    ]),
  },
  {
    id: 'rappers',
    name: 'Rappers',
    emoji: '🎤',
    tagline: 'Draft the GOAT lineup',
    gradient: 'from-yellow-500 to-amber-600',
    groups: [
      { id: 'east', name: 'East Coast', emoji: '🗽' },
      { id: 'west', name: 'West Coast', emoji: '🌴' },
      { id: 'south', name: 'South', emoji: '🍑' },
      { id: 'modern', name: 'New School', emoji: '🔥' },
    ],
    items: items([
      ['Jay-Z', undefined, '🇧', 'east'],
      ['Nas', undefined, '🗽', 'east'],
      ['The Notorious B.I.G.', undefined, '👑', 'east'],
      ['50 Cent', undefined, '💵', 'east'],
      ['Wu-Tang Clan', undefined, '🐝', 'east'],
      ['A$AP Rocky', undefined, '🏴', 'east'],
      ['Kendrick Lamar', undefined, '👑', 'west'],
      ['Tupac', undefined, '✌️', 'west'],
      ['Dr. Dre', undefined, '🎚️', 'west'],
      ['Snoop Dogg', undefined, '🌿', 'west'],
      ['Ice Cube', undefined, '🧊', 'west'],
      ['Tyler, the Creator', undefined, '🐝', 'west'],
      ['Doja Cat', undefined, '🐈', 'west'],
      ['Lil Wayne', undefined, '🛹', 'south'],
      ['Andre 3000', undefined, '🎩', 'south'],
      ['T.I.', undefined, '👑', 'south'],
      ['Megan Thee Stallion', undefined, '🐎', 'south'],
      ['Gucci Mane', undefined, '🍦', 'south'],
      ['Future', undefined, '🚀', 'south'],
      ['Drake', undefined, '🦉', 'modern'],
      ['J. Cole', undefined, '🌳', 'modern'],
      ['Kanye West', undefined, '🐻', 'modern'],
      ['Eminem', undefined, '🔪', 'modern'],
      ['Travis Scott', undefined, '🌵', 'modern'],
      ['Nicki Minaj', undefined, '💖', 'modern'],
      ['Cardi B', undefined, '💅', 'modern'],
      ['21 Savage', undefined, '🔪', 'modern'],
      ['Lil Baby', undefined, '🍼', 'modern'],
      ['Playboi Carti', undefined, '🧛', 'modern'],
      ['Metro Boomin', undefined, '🎛️', 'modern'],
    ]),
  },
  {
    id: 'tvshows',
    name: 'TV Shows',
    emoji: '📺',
    tagline: 'Draft the perfect binge list',
    gradient: 'from-blue-500 to-indigo-600',
    groups: [
      { id: 'drama', name: 'Drama', emoji: '🎭' },
      { id: 'comedy', name: 'Comedy', emoji: '😂' },
      { id: 'scifi-fantasy', name: 'Sci-Fi & Fantasy', emoji: '🐉' },
      { id: 'crime', name: 'Crime & Thriller', emoji: '🔪' },
      { id: 'animated', name: 'Animated', emoji: '🎨' },
    ],
    items: items([
      ['Succession', undefined, '💼', 'drama'],
      ['Mad Men', undefined, '🥃', 'drama'],
      ['The Crown', undefined, '👑', 'drama'],
      ['This Is Us', undefined, '🫂', 'drama'],
      ['Friday Night Lights', undefined, '🏈', 'drama'],
      ['The Office', undefined, '📎', 'comedy'],
      ['Friends', undefined, '☕', 'comedy'],
      ['Seinfeld', undefined, '🥨', 'comedy'],
      ['Ted Lasso', undefined, '⚽', 'comedy'],
      ['Parks and Recreation', undefined, '🏞️', 'comedy'],
      ['It’s Always Sunny', undefined, '🍺', 'comedy'],
      ['Curb Your Enthusiasm', undefined, '😬', 'comedy'],
      ['Game of Thrones', undefined, '🐉', 'scifi-fantasy'],
      ['Stranger Things', undefined, '🚲', 'scifi-fantasy'],
      ['The Last of Us', undefined, '🍄', 'scifi-fantasy'],
      ['Severance', undefined, '🧠', 'scifi-fantasy'],
      ['The Mandalorian', undefined, '🪖', 'scifi-fantasy'],
      ['House of the Dragon', undefined, '🔥', 'scifi-fantasy'],
      ['Black Mirror', undefined, '🪞', 'scifi-fantasy'],
      ['Breaking Bad', undefined, '🧪', 'crime'],
      ['The Sopranos', undefined, '🦆', 'crime'],
      ['The Wire', undefined, '🎧', 'crime'],
      ['Better Call Saul', undefined, '⚖️', 'crime'],
      ['True Detective', undefined, '🕵️', 'crime'],
      ['Ozark', undefined, '💵', 'crime'],
      ['The Bear', undefined, '🔪', 'crime'],
      ['Avatar: The Last Airbender', undefined, '🌊', 'animated'],
      ['Rick and Morty', undefined, '🥒', 'animated'],
      ['The Simpsons', undefined, '🍩', 'animated'],
      ['BoJack Horseman', undefined, '🐴', 'animated'],
      ['Arcane', undefined, '⚙️', 'animated'],
      ['South Park', undefined, '🏔️', 'animated'],
    ]),
  },
  {
    id: 'cocktails',
    name: 'Cocktails',
    emoji: '🍸',
    tagline: 'Stock the dream bar',
    gradient: 'from-fuchsia-500 to-pink-600',
    groups: [
      { id: 'classic', name: 'Classics', emoji: '🥃' },
      { id: 'tropical', name: 'Tropical', emoji: '🏝️' },
      { id: 'sour-citrus', name: 'Sour & Citrus', emoji: '🍋' },
      { id: 'bubbly', name: 'Bubbly & Spritz', emoji: '🫧' },
    ],
    items: items([
      ['Old Fashioned', undefined, '🥃', 'classic'],
      ['Negroni', undefined, '🍊', 'classic'],
      ['Manhattan', undefined, '🍒', 'classic'],
      ['Martini', undefined, '🍸', 'classic'],
      ['Espresso Martini', undefined, '☕', 'classic'],
      ['Sazerac', undefined, '🥃', 'classic'],
      ['Boulevardier', undefined, '🟤', 'classic'],
      ['Piña Colada', undefined, '🥥', 'tropical'],
      ['Mai Tai', undefined, '🏝️', 'tropical'],
      ['Mojito', undefined, '🌿', 'tropical'],
      ['Daiquiri', undefined, '🍓', 'tropical'],
      ['Hurricane', undefined, '🌪️', 'tropical'],
      ['Painkiller', undefined, '🌴', 'tropical'],
      ['Margarita', undefined, '🍹', 'sour-citrus'],
      ['Whiskey Sour', undefined, '🍋', 'sour-citrus'],
      ['Paloma', undefined, '🍈', 'sour-citrus'],
      ['Cosmopolitan', undefined, '💗', 'sour-citrus'],
      ['Gimlet', undefined, '🟢', 'sour-citrus'],
      ['Tom Collins', undefined, '🍋', 'sour-citrus'],
      ['Sidecar', undefined, '🍊', 'sour-citrus'],
      ['Moscow Mule', undefined, '🫚', 'bubbly'],
      ['Aperol Spritz', undefined, '🧡', 'bubbly'],
      ['Gin & Tonic', undefined, '🫧', 'bubbly'],
      ['Mimosa', undefined, '🥂', 'bubbly'],
      ['French 75', undefined, '🍾', 'bubbly'],
      ['Bellini', undefined, '🍑', 'bubbly'],
      ['Long Island Iced Tea', undefined, '🧊', 'bubbly'],
      ['Dark ’n’ Stormy', undefined, '⛈️', 'bubbly'],
    ]),
  },
  {
    id: 'pizza',
    name: 'Pizza Toppings',
    emoji: '🍕',
    tagline: 'Build the ultimate pie',
    gradient: 'from-amber-500 to-red-600',
    groups: [
      { id: 'meats', name: 'Meats', emoji: '🥓' },
      { id: 'veggies', name: 'Veggies', emoji: '🫑' },
      { id: 'cheese-sauce', name: 'Cheese & Sauce', emoji: '🧀' },
      { id: 'wildcards', name: 'Wildcards', emoji: '🍍' },
    ],
    items: items([
      ['Pepperoni', undefined, '🔴', 'meats'],
      ['Sausage', undefined, '🌭', 'meats'],
      ['Bacon', undefined, '🥓', 'meats'],
      ['Ham', undefined, '🍖', 'meats'],
      ['Meatball', undefined, '🟤', 'meats'],
      ['Prosciutto', undefined, '🥩', 'meats'],
      ['Salami', undefined, '🍕', 'meats'],
      ['BBQ Chicken', undefined, '🍗', 'meats'],
      ['Mushroom', undefined, '🍄', 'veggies'],
      ['Onion', undefined, '🧅', 'veggies'],
      ['Green Pepper', undefined, '🫑', 'veggies'],
      ['Black Olives', undefined, '🫒', 'veggies'],
      ['Jalapeño', undefined, '🌶️', 'veggies'],
      ['Spinach', undefined, '🥬', 'veggies'],
      ['Fresh Basil', undefined, '🌿', 'veggies'],
      ['Garlic', undefined, '🧄', 'veggies'],
      ['Roasted Red Peppers', undefined, '🟥', 'veggies'],
      ['Artichoke', undefined, '🌱', 'veggies'],
      ['Extra Cheese', undefined, '🧀', 'cheese-sauce'],
      ['Fresh Mozzarella', undefined, '⚪', 'cheese-sauce'],
      ['Feta', undefined, '🧀', 'cheese-sauce'],
      ['Ricotta', undefined, '🥛', 'cheese-sauce'],
      ['Parmesan', undefined, '🧀', 'cheese-sauce'],
      ['Pesto Base', undefined, '🌿', 'cheese-sauce'],
      ['White Sauce', undefined, '🤍', 'cheese-sauce'],
      ['Pineapple', 'fight me', '🍍', 'wildcards'],
      ['Anchovies', 'the villain', '🐟', 'wildcards'],
      ['Hot Honey', undefined, '🍯', 'wildcards'],
      ['Fried Egg', undefined, '🍳', 'wildcards'],
      ['Buffalo Sauce', undefined, '🔥', 'wildcards'],
      ['Truffle Oil', undefined, '🍄', 'wildcards'],
    ]),
  },
  {
    id: 'cars',
    name: 'Cars',
    emoji: '🚗',
    tagline: 'Draft your dream garage',
    gradient: 'from-slate-400 to-zinc-600',
    groups: [
      { id: 'supercars', name: 'Supercars', emoji: '🏎️' },
      { id: 'sports', name: 'Sports & Muscle', emoji: '🐎' },
      { id: 'ev', name: 'Electric', emoji: '⚡' },
      { id: 'offroad', name: 'Off-Road & Trucks', emoji: '🛻' },
      { id: 'daily', name: 'Daily Drivers', emoji: '🛞' },
    ],
    items: items([
      ['Lamborghini Huracán', undefined, '🐂', 'supercars'],
      ['Ferrari F8', undefined, '🐎', 'supercars'],
      ['McLaren 720S', undefined, '🟠', 'supercars'],
      ['Bugatti Chiron', undefined, '💨', 'supercars'],
      ['Aston Martin Vantage', undefined, '🇬🇧', 'supercars'],
      ['Audi R8', undefined, '⭕', 'supercars'],
      ['Porsche 911', undefined, '🏁', 'sports'],
      ['Ford Mustang', undefined, '🐎', 'sports'],
      ['Chevy Corvette', undefined, '🦅', 'sports'],
      ['Toyota Supra', undefined, '🇯🇵', 'sports'],
      ['BMW M3', undefined, '🔵', 'sports'],
      ['Dodge Charger', undefined, '💨', 'sports'],
      ['Nissan GT-R', undefined, '🏮', 'sports'],
      ['Mazda Miata', undefined, '🛣️', 'sports'],
      ['Tesla Model 3', undefined, '⚡', 'ev'],
      ['Tesla Model S Plaid', undefined, '🔋', 'ev'],
      ['Rivian R1T', undefined, '🔋', 'ev'],
      ['Lucid Air', undefined, '💨', 'ev'],
      ['Porsche Taycan', undefined, '⚡', 'ev'],
      ['Hyundai Ioniq 5', undefined, '🔌', 'ev'],
      ['Jeep Wrangler', undefined, '🏔️', 'offroad'],
      ['Toyota Tacoma', undefined, '🛻', 'offroad'],
      ['Ford F-150 Raptor', undefined, '🦖', 'offroad'],
      ['Range Rover', undefined, '🏞️', 'offroad'],
      ['Land Cruiser', undefined, '⛰️', 'offroad'],
      ['Ford Bronco', undefined, '🐴', 'offroad'],
      ['Honda Civic', undefined, '🛞', 'daily'],
      ['Toyota Camry', undefined, '🚙', 'daily'],
      ['Subaru Outback', undefined, '🌲', 'daily'],
      ['Honda CR-V', undefined, '🚗', 'daily'],
      ['Mazda CX-5', undefined, '🛣️', 'daily'],
    ]),
  },
  {
    id: 'candy',
    name: 'Candy',
    emoji: '🍬',
    tagline: 'Raid the candy aisle',
    gradient: 'from-pink-500 to-fuchsia-600',
    groups: [
      { id: 'chocolate', name: 'Chocolate', emoji: '🍫' },
      { id: 'gummy', name: 'Gummy & Chewy', emoji: '🐻' },
      { id: 'sour', name: 'Sour', emoji: '😝' },
      { id: 'hard-fruity', name: 'Hard & Fruity', emoji: '🌈' },
    ],
    items: items([
      ['Reese’s', undefined, '🥜', 'chocolate'],
      ['KitKat', undefined, '🍫', 'chocolate'],
      ['Snickers', undefined, '🥜', 'chocolate'],
      ['M&M’s', undefined, '🔴', 'chocolate'],
      ['Twix', undefined, '🍪', 'chocolate'],
      ['Hershey’s', undefined, '🍫', 'chocolate'],
      ['Milky Way', undefined, '🌌', 'chocolate'],
      ['Butterfinger', undefined, '🧡', 'chocolate'],
      ['Crunch', undefined, '🟫', 'chocolate'],
      ['3 Musketeers', undefined, '⚔️', 'chocolate'],
      ['Gummy Bears', undefined, '🐻', 'gummy'],
      ['Swedish Fish', undefined, '🐟', 'gummy'],
      ['Twizzlers', undefined, '🔴', 'gummy'],
      ['Sour Patch Kids', undefined, '😝', 'gummy'],
      ['Skittles', undefined, '🌈', 'gummy'],
      ['Starburst', undefined, '⭐', 'gummy'],
      ['Haribo', undefined, '🐻', 'gummy'],
      ['Airheads', undefined, '🌬️', 'gummy'],
      ['Warheads', undefined, '☢️', 'sour'],
      ['Sour Skittles', undefined, '🌈', 'sour'],
      ['Lemonheads', undefined, '🍋', 'sour'],
      ['Sour Worms', undefined, '🪱', 'sour'],
      ['Toxic Waste', undefined, '🛢️', 'sour'],
      ['Cry Baby', undefined, '😭', 'sour'],
      ['Jolly Ranchers', undefined, '💎', 'hard-fruity'],
      ['Nerds', undefined, '🤓', 'hard-fruity'],
      ['Werther’s Original', undefined, '🧈', 'hard-fruity'],
      ['Life Savers', undefined, '🛟', 'hard-fruity'],
      ['Dum-Dums', undefined, '🍭', 'hard-fruity'],
      ['Jelly Belly', undefined, '🫘', 'hard-fruity'],
      ['Tootsie Pop', undefined, '🦉', 'hard-fruity'],
    ]),
  },
]

export function getCategory(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id)
}
export function getItem(categoryId: string, itemId: string): DraftItem | undefined {
  return getCategory(categoryId)?.items.find((i) => i.id === itemId)
}
