import type { Category, DraftItem } from '../lib/types'

let _id = 0
function items(list: Array<[string, string?, string?]>): DraftItem[] {
  return list.map(([name, subtitle, emoji]) => ({
    id: `i${_id++}`,
    name,
    subtitle,
    emoji,
  }))
}

export const CATEGORIES: Category[] = [
  {
    id: 'restaurants',
    name: 'Restaurants',
    emoji: '🍔',
    tagline: 'Draft your dream food court',
    gradient: 'from-orange-500 to-rose-500',
    items: items([
      ['In-N-Out', 'Burgers', '🍔'],
      ['Chipotle', 'Build-a-burrito', '🌯'],
      ['Shake Shack', 'Burgers + shakes', '🥤'],
      ['Olive Garden', 'Endless breadsticks', '🍝'],
      ['Chick-fil-A', 'Sandwiches', '🐔'],
      ['Cheesecake Factory', 'The novel-menu', '🍰'],
      ['Taco Bell', 'Late night legend', '🌮'],
      ['Five Guys', 'Burgers + fries', '🍟'],
      ["Domino's", 'Pizza', '🍕'],
      ['Panda Express', 'Orange chicken', '🥡'],
      ['Raising Cane’s', 'Chicken fingers', '🍗'],
      ['Texas Roadhouse', 'Steaks + rolls', '🥩'],
      ['IHOP', 'Pancakes 24/7', '🥞'],
      ['Sweetgreen', 'Salad flex', '🥗'],
      ['Popeyes', 'The chicken sandwich', '🍗'],
      ['Waffle House', 'Scattered, smothered', '🧇'],
    ]),
  },
  {
    id: 'nfl',
    name: 'NFL Teams',
    emoji: '🏈',
    tagline: 'Build the league from scratch',
    gradient: 'from-emerald-500 to-teal-500',
    items: items([
      ['Chiefs', 'Kansas City', '🔴'],
      ['Eagles', 'Philadelphia', '🦅'],
      ['49ers', 'San Francisco', '⛏️'],
      ['Cowboys', 'Dallas', '⭐'],
      ['Bills', 'Buffalo', '🦬'],
      ['Ravens', 'Baltimore', '🐦‍⬛'],
      ['Lions', 'Detroit', '🦁'],
      ['Dolphins', 'Miami', '🐬'],
      ['Packers', 'Green Bay', '🧀'],
      ['Bengals', 'Cincinnati', '🐅'],
      ['Steelers', 'Pittsburgh', '⚫'],
      ['Vikings', 'Minnesota', '🛡️'],
      ['Jaguars', 'Jacksonville', '🐆'],
      ['Chargers', 'Los Angeles', '⚡'],
      ['Seahawks', 'Seattle', '🦅'],
      ['Bears', 'Chicago', '🐻'],
    ]),
  },
  {
    id: 'movies',
    name: 'Movies',
    emoji: '🍿',
    tagline: 'Draft the ultimate watchlist',
    gradient: 'from-fuchsia-500 to-purple-600',
    items: items([
      ['The Dark Knight', '2008', '🦇'],
      ['Inception', '2010', '🌀'],
      ['Pulp Fiction', '1994', '🔫'],
      ['The Godfather', '1972', '🍷'],
      ['Spirited Away', '2001', '🐉'],
      ['Parasite', '2019', '🪜'],
      ['Interstellar', '2014', '🚀'],
      ['Forrest Gump', '1994', '🍫'],
      ['The Matrix', '1999', '💊'],
      ['Goodfellas', '1990', '🃏'],
      ['La La Land', '2016', '🎹'],
      ['Mad Max: Fury Road', '2015', '🏜️'],
      ['Whiplash', '2014', '🥁'],
      ['Get Out', '2017', '🫖'],
      ['Everything Everywhere', '2022', '🥯'],
      ['Jurassic Park', '1993', '🦖'],
    ]),
  },
  {
    id: 'travel',
    name: 'Travel Spots',
    emoji: '✈️',
    tagline: 'Draft your bucket list',
    gradient: 'from-sky-500 to-blue-600',
    items: items([
      ['Tokyo', 'Japan', '🗼'],
      ['Paris', 'France', '🗼'],
      ['Rome', 'Italy', '🏛️'],
      ['New York', 'USA', '🗽'],
      ['Bali', 'Indonesia', '🏝️'],
      ['Reykjavik', 'Iceland', '🌋'],
      ['Cape Town', 'South Africa', '⛰️'],
      ['Barcelona', 'Spain', '🏖️'],
      ['Queenstown', 'New Zealand', '🪂'],
      ['Marrakech', 'Morocco', '🕌'],
      ['Kyoto', 'Japan', '⛩️'],
      ['Banff', 'Canada', '🏔️'],
      ['Santorini', 'Greece', '🇬🇷'],
      ['Rio de Janeiro', 'Brazil', '🎉'],
      ['Patagonia', 'Argentina/Chile', '🥾'],
      ['Lisbon', 'Portugal', '🚋'],
    ]),
  },
  {
    id: 'icecream',
    name: 'Ice Cream',
    emoji: '🍦',
    tagline: 'Scoop the perfect lineup',
    gradient: 'from-pink-400 to-rose-400',
    items: items([
      ['Cookies & Cream', undefined, '🍪'],
      ['Mint Choc Chip', undefined, '🌱'],
      ['Cookie Dough', undefined, '🍪'],
      ['Salted Caramel', undefined, '🧂'],
      ['Chocolate', undefined, '🍫'],
      ['Vanilla', 'don’t sleep on it', '🤍'],
      ['Strawberry', undefined, '🍓'],
      ['Pistachio', undefined, '🥜'],
      ['Rocky Road', undefined, '🪨'],
      ['Coffee', undefined, '☕'],
      ['Birthday Cake', undefined, '🎂'],
      ['Mango Sorbet', undefined, '🥭'],
      ['Neapolitan', undefined, '🟤'],
      ['Butter Pecan', undefined, '🧈'],
    ]),
  },
  {
    id: 'games',
    name: 'Video Games',
    emoji: '🎮',
    tagline: 'Draft the GOAT library',
    gradient: 'from-indigo-500 to-violet-600',
    items: items([
      ['The Legend of Zelda: BOTW', undefined, '🗡️'],
      ['Elden Ring', undefined, '⚔️'],
      ['Minecraft', undefined, '⛏️'],
      ['Super Mario Odyssey', undefined, '🍄'],
      ['God of War', undefined, '🪓'],
      ['Hollow Knight', undefined, '🪲'],
      ['Portal 2', undefined, '🟠'],
      ['Stardew Valley', undefined, '🌾'],
      ['Red Dead Redemption 2', undefined, '🤠'],
      ['Hades', undefined, '🔥'],
      ['Mario Kart 8', undefined, '🏎️'],
      ['Celeste', undefined, '🏔️'],
      ['Tetris', undefined, '🟦'],
      ['Animal Crossing', undefined, '🍃'],
    ]),
  },
  {
    id: 'snacks',
    name: 'Snacks',
    emoji: '🍿',
    tagline: 'Stock the ultimate pantry',
    gradient: 'from-amber-500 to-orange-600',
    items: items([
      ['Doritos', 'Nacho Cheese', '🔺'],
      ['Pringles', undefined, '🥫'],
      ['Oreos', undefined, '🍪'],
      ['Goldfish', undefined, '🐠'],
      ['Cheez-Its', undefined, '🧀'],
      ['Takis', undefined, '🌶️'],
      ['Pop-Tarts', undefined, '🍓'],
      ['Reese’s', undefined, '🥜'],
      ['Sour Patch Kids', undefined, '😝'],
      ['Ritz', undefined, '⭕'],
      ['Combos', undefined, '🥨'],
      ['Skittles', undefined, '🌈'],
      ['Cheetos', undefined, '🐆'],
      ['Trail Mix', undefined, '🥜'],
    ]),
  },
  {
    id: 'pets',
    name: 'Dog Breeds',
    emoji: '🐶',
    tagline: 'Assemble the goodest boys',
    gradient: 'from-yellow-500 to-amber-600',
    items: items([
      ['Golden Retriever', undefined, '🦮'],
      ['Corgi', undefined, '🌭'],
      ['French Bulldog', undefined, '🦇'],
      ['Husky', undefined, '🐺'],
      ['Dachshund', undefined, '🌭'],
      ['Labrador', undefined, '🦴'],
      ['Border Collie', undefined, '🧠'],
      ['Pug', undefined, '😤'],
      ['Shiba Inu', undefined, '🔥'],
      ['Great Dane', undefined, '🦒'],
      ['Beagle', undefined, '👃'],
      ['Pomeranian', undefined, '☁️'],
      ['Australian Shepherd', undefined, '🐑'],
      ['Bernese Mountain Dog', undefined, '⛰️'],
    ]),
  },
]

export function getCategory(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id)
}

export function getItem(categoryId: string, itemId: string): DraftItem | undefined {
  return getCategory(categoryId)?.items.find((i) => i.id === itemId)
}
